name: vntapp-Linux

on:
   workflow_dispatch:
    inputs:
      repo:
        description: '请输入vntAPP源码仓库'
        required: true
        default: 'cn1095/VntApp'
      tag:
        description: '请输入仓库分支或版本号'
        required: true
        default: 'Location'
env:
  CARGO_TERM_COLOR: always
  TZ: Asia/Shanghai
  repo: "${{ github.event.inputs.repo }}"
  tag: "${{ github.event.inputs.tag }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 设置Flutter环境
        uses: subosito/flutter-action@v2
        with:
         channel: stable
         flutter-version: 3.22.0
         
      - name: 克隆源码
        run: git clone -b "${{ env.tag }}" "https://github.com/${{ env.repo }}" /opt/vnt

      - name: 安装 musl 并设置为默认编译器
        run: |
          sudo apt-get update
          sudo apt-get install -y musl musl-tools musl-dev 
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/musl-gcc 100
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/musl-gcc 100
    
      - name: 构建
        run: |
         cd /opt/vnt
         sudo apt-get update
         sudo apt-get install -y libgtk-3-dev build-essential libayatana-appindicator3-dev --fix-missing
         flutter pub get
         CC=musl-gcc CXX=musl-g++ flutter build linux --release -v
         
         #mkdir -p /opt/vntAPP
         #mv -f /opt/vnt/build/linux/x64/release/bundle /opt/vntAPP/vntAPP-Linux-x86_64
    
      - name : 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: vntAPP-Linux
         path: /opt/vnt/build/linux/x64/release/bundle/*
